# Generated by Django 3.2.6 on 2021-08-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='new_field',
            field=models.CharField(default='nic3', max_length=50),
        ),
    ]
