# Generated by Django 3.2.6 on 2021-08-20 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_run_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='new_field',
        ),
    ]
