# Generated by Django 3.2.6 on 2021-08-21 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_remove_run_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='duration',
        ),
        migrations.AddField(
            model_name='run',
            name='minutes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4320)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='seconds',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
