# Generated by Django 3.2.6 on 2021-08-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0007_alter_run_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ('-unix_date',)},
        ),
        migrations.RemoveField(
            model_name='run',
            name='date',
        ),
        migrations.AddField(
            model_name='run',
            name='unix_date',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
