# Generated by Django 3.2.6 on 2021-08-25 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0008_auto_20210825_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='unix_date',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1629896344.9449098)]),
        ),
    ]
