# Generated by Django 3.2.6 on 2021-08-30 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_rename_followers_follows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follows',
            options={'verbose_name': 'Follows', 'verbose_name_plural': 'Follows'},
        ),
        migrations.AddField(
            model_name='follows',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
