# Generated by Django 3.2.6 on 2021-08-31 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_remove_follows_follow_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='follows',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, default=[], related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
