# Generated by Django 3.2.6 on 2021-08-31 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_follows_follow_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follows',
            name='follow_requests',
        ),
        migrations.AddField(
            model_name='follows',
            name='recieved_follow_requests',
            field=models.ManyToManyField(blank=True, related_name='recieved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follows',
            name='sent_follow_requests',
            field=models.ManyToManyField(blank=True, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
