# Generated by Django 3.2.6 on 2021-09-03 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20210831_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='follows',
            name='favorite_followed_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_followed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
