# Generated by Django 3.2.6 on 2021-09-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='distance_unit',
            field=models.CharField(default='MILES', max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='language',
            field=models.CharField(default='ENGLISH', max_length=100),
        ),
    ]
