# Generated by Django 3.2.6 on 2021-09-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210904_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='distance_unit',
            new_name='unit',
        ),
    ]
