# Generated by Django 3.2.6 on 2021-09-07 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210907_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='weekly_goal',
            field=models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
