# Generated by Django 3.2.6 on 2021-09-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_follows_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='verification_code',
            field=models.CharField(default=70783, max_length=5),
        ),
    ]
