# Generated by Django 3.2.6 on 2021-09-19 20:50

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_follows_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='verification_code',
            field=models.CharField(default=users.models.generate_random_verification_code, max_length=6),
        ),
    ]
