# Generated by Django 3.2.6 on 2021-09-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_follows_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='follows',
            name='last_sent_email',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
